services:
  koffan:
    container_name: koffan
    hostname: koffan
    environment:
      - APP_PASSWORD=${PASSWORD}
    volumes:
      - /mnt/nvme/appdata/koffan:/data
    image: ghcr.io/pansalut/koffan:latest
    restart: unless-stopped
networks:
  default:
    name: proxy-net
    external: true
