services:
  borgmatic:
    image: ghcr.io/borgmatic-collective/borgmatic
    container_name: borgmatic
    volumes:
      - /lab/archive/borgmatic/data:/mnt/borg-repository
      - /lab/archive/borgmatic/cache:/root/.cache/borg
      - /lab/appdata/borgmatic/.config:/etc/borgmatic.d/
      - /lab/appdata/borgmatic/borg_keys:/root/.config/borg
      - /lab/appdata/borgmatic/.ssh:/root/.ssh
      # Source Dirs
      - /lab/appdata:/src/appdata:ro
      - /lab/immmich/:/src/photos:ro
      - /lab/archive/nextcloud:/src/nextcloud:ro
      - /lab/data/:/src/data#:ro
    environment:
      - TZ=Europe/London
      - BORG_PASSPHRASE=${BORG_PASSPHRASE}
    networks:
      - db_network
    restart: unless-stopped
networks:
  db_network:
    external: true
