services:
  borgmatic:
    image: ghcr.io/borgmatic-collective/borgmatic
    container_name: borgmatic
    volumes:
      - /lab/pool/archive/borg/data:/mnt/borg-repository
      - /lab/pool/archive/borg/cache:/root/.cache/borg
      - /lab/appdata/borgmatic/.config:/etc/borgmatic.d/
      - /lab/appdata/borgmatic/borg_keys:/root/.config/borg
      - /lab/appdata/borgmatic/.ssh:/root/.ssh
      # Source Dirs
      - /lab/appdata:/src/appdata
      - /lab/immich/:/src/photos
      - /lab/pool/archive/nextcloud:/src/nextcloud
      - /lab/data/:/src/data
    environment:
      - TZ=Europe/London
      - BORG_PASSPHRASE=${BORG_PASSPHRASE}
    networks:
      - db_network
    restart: unless-stopped
networks:
  db_network:
    external: true
