services:
  motioneye:
    container_name: motioneye
    restart: unless-stopped
    image: ghcr.io/motioneye-project/motioneye:edge
    ports:
      - 8765:8765
    volumes:
      - /lab/appdata/motioneye/etc:/etc/motioneye
      - /lab/appdata/motioneye/var_lib:/var/lib/motioneye
