services:
  reitti:
    image: dedicatedcode/reitti:latest
    container_name: reitti
    ports:
      - 8088:8080
    depends_on:
      postgis:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
      tile-cache:
        condition: service_healthy
    volumes:
     - /lab/appdata/reitti/reitti-data:/data/
    environment:
      POSTGIS_USER: reitti
      POSTGIS_PASSWORD: reitti
      POSTGIS_DB: reittidb
      POSTGIS_HOST: postgis
    networks:
      - default
  postgis:
    image: postgis/postgis:17-3.5-alpine
    container_name: reitti-db
    environment:
      POSTGRES_USER: reitti
      POSTGRES_PASSWORD: reitti
      POSTGRES_DB: reittidb
    volumes:
      - /lab/appdata/reitti/postgis-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reitti -d reittidb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
      - db_network
  redis:
    image: redis:7-alpine
    container_name: reitti-redis
    volumes:
      - /lab/appdata/reitti/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
  tile-cache:
    image: dedicatedcode/reitti-tile-cache:latest
    container_name: reitti-tc
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1/osm/0/0/0.png"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /lab/appdata/reitti/titlecache:/var/cache/nginx
    networks:
      - default

networks:
  default:
    driver: bridge
  db_network:
    external: true
