services:
  zen:
    image: lscr.io/linuxserver/zen:latest
    container_name: zen
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /lab/appdata/zen:/config
    shm_size: "1gb"
    restart: unless-stopped
networks:
  default:
    name: proxy-net
    external: true
