services:
  modmanager:
    env: stack.env
    image: lscr.io/linuxserver/modmanager:latest
    container_name: modmanager
    environment:
      - DOCKER_MODS=linuxserver/mods:swag-dashboard|linuxserver/mods:universal-docker
    volumes:
      - ${DIR}:/modcache
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
networks: {}
