services:
  zen:
    hostname: zenxrdp
    container_name: zenxrdp
    image: ajb3932/zenxrdp:latest
    ports:
      - "3390:3389"
    environment:
      - RDP_PASSWORD=${RDP_PW}
    volumes:
      - /lab/appdata/zenxrdp/data:/home/rdpuser/.zen
      - /lab/appdata/zenxrdp/downloads:/home/rdpuser/Downloads
    restart: unless-stopped
